from . import (
    test_assets_management,
    test_attrs_views,
    test_filters,
    test_fix_views,
    test_ir_act_server_conversion,
    test_manual_fields_start_with_x_,
    test_mock_crawl,
    test_module_state,
    test_read_group_refactor,
    test_rem,
    test_res_partner_bank,
    test_transient_model_access,
    test_translate,
    test_versions,
)
