from odoo.upgrade import util

DEACTIVATE_TAXES = (
    "au_tax_sale_inc_10",
    "au_tax_purchase_inc_10_service",
    "au_tax_purchase_inc_10_service_tpar",
    "au_tax_purchase_inc_10_service_tpar_no_abn",
    "tax_template_out_aproxtrib_fed_incl_goods",
    "tax_template_out_aproxtrib_state_incl_goods",
    "tax_template_out_cofins_incl_goods",
    "tax_template_out_cofins_deson_incl_goods",
    "tax_template_out_cofins_st_incl_goods",
    "tax_template_out_icms_incl_goods",
    "tax_template_out_icms_credsn_incl_goods",
    "tax_template_out_icms_deson_incl_goods",
    "tax_template_out_icms_difa_dest_incl_goods",
    "tax_template_out_icms_difa_fcp_incl_goods",
    "tax_template_out_icms_difa_remet_incl_goods",
    "tax_template_out_icms_eff_incl_goods",
    "tax_template_out_icms_fcp_incl_goods",
    "tax_template_out_icms_own_payer_incl_goods",
    "tax_template_out_icms_part_incl_goods",
    "tax_template_out_icms_rf_incl_goods",
    "tax_template_out_icms_st_incl_goods",
    "tax_template_out_icms_st_fcp_incl_goods",
    "tax_template_out_icms_st_fcppart_incl_goods",
    "tax_template_out_icms_st_part_incl_goods",
    "tax_template_out_icms_st_sd_incl_goods",
    "tax_template_out_icms_st_sd_fcp_incl_goods",
    "tax_template_out_ii_incl_goods",
    "tax_template_out_iof_incl_goods",
    "tax_template_out_ipi_incl_goods",
    "tax_template_out_ipi_returned_incl_goods",
    "tax_template_out_pis_incl_goods",
    "tax_template_out_pis_deson_incl_goods",
    "tax_template_out_pis_st_incl_goods",
    "tax_template_out_aproxtrib_city_incl_service",
    "tax_template_out_pis_rf_incl_service",
    "tax_template_out_cofins_rf_incl_service",
    "tax_template_out_csll_incl_service",
    "tax_template_out_csll_rf_incl_service",
    "tax_template_out_iss_incl_service",
    "tax_template_out_iss_rf_incl_service",
    "tax_template_out_ir_pj_incl_service",
    "tax_template_out_ir_rf_incl_service",
    "tax_template_out_cprb_incl_service",
    "tax_template_out_cprb_rf_incl_service",
    "tax_template_out_inss_ar_incl_service",
    "tax_template_out_inss_rf_incl_service",
    "vat_25_incl",
    "vat_25_purchase_incl",
    "vat_25_invest_incl",
    "vat_37_incl",
    "vat_37_purchase_incl",
    "vat_37_invest_incl",
    "vat_77_incl",
    "vat_77_purchase_incl",
    "vat_77_invest_incl",
    "vat_sale_26_incl",
    "vat_purchase_26_incl",
    "vat_purchase_26_invest_incl",
    "vat_sale_38_incl",
    "vat_purchase_38_incl",
    "vat_purchase_38_invest_incl",
    "vat_sale_81_incl",
    "vat_purchase_81_incl",
    "vat_purchase_81_invest_incl",
    "l10n_cn_sales_included_13",
    "l10n_cn_sales_included_9",
    "l10n_cn_sales_included_6",
    "l10n_cn_tax_large_bis_sales_included_13",
    "l10n_cn_tax_large_bis_sales_included_9",
    "l10n_cn_tax_large_bis_sales_included_6",
    "l10n_cz_not_included_vat",
    "tax_ust_19_taxinclusive_skr03",
    "tax_ust_7_taxinclusive_skr03",
    "tax_vst_19_taxinclusive_skr03",
    "tax_vst_7_taxinclusive_skr03",
    "tax_ust_19_taxinclusive_skr04",
    "tax_ust_7_taxinclusive_skr04",
    "tax_vst_19_taxinclusive_skr04",
    "tax_vst_7_taxinclusive_skr04",
    "tax_18_sale_incl",
    "tax_18_purch_incl",
    "tax_16_purch_incl",
    "tax_9_purch_incl",
    "tax_8_purch_incl",
    "tax_18_purch_serv_incl",
    "tax_dom_purchase_brutto_25_5",
    "tax_dom_purchase_brutto_24",
    "tax_dom_purchase_brutto_14",
    "tax_dom_purchase_brutto_10",
    "l10n_jp_tax_sale_incl_8",
    "l10n_jp_tax_sale_incl_10",
    "l10n_jp_tax_purchase_incl_8",
    "l10n_jp_tax_purchase_incl_10",
    "l10n_kz_tax_vat_12_sale_included",
    "l10n_kz_tax_vat_12_purchase_included",
    "l10n_kz_tax_vat_20_sale_included",
    "l10n_kz_tax_vat_20_purchase_included",
    "l10n_kz_tax_vat_12_sale_included_export",
    "l10n_kz_tax_vat_12_purchase_included_import",
    "l10n_kz_tax_vat_20_sale_included_export",
    "l10n_kz_tax_vat_20_purchase_included_import",
    "l10n_kz_tax_vat_12_sale_included_eeu",
    "l10n_kz_tax_vat_12_purchase_included_eeu",
    "l10n_kz_tax_vat_20_sale_included_eeu",
    "l10n_kz_tax_vat_20_purchase_included_eeu",
    "btw_9_buy_incl",
    "btw_21_buy_incl",
    "nz_tax_sale_inc_15",
    "nz_tax_purchase_inc_15",
    "sale_tax_igv_18_included",
    "purchase_tax_igv_18_included",
    "tw_tax_sale_inc_5",
    "tw_tax_purchase_inc_5",
    "sale_tax_template_vat20incl_psbo",
    "sale_tax_template_vat14incl_psbo",
    "sale_tax_template_vat7incl_psbo",
    "purchase_tax_template_vat20incl_psbo",
    "purchase_tax_template_vat14incl_psbo",
    "purchase_tax_template_vat7incl_psbo",
)


def migrate(cr, version):
    util.create_column(cr, "res_company", "account_price_include", "varchar", default="tax_excluded")
    util.create_column(cr, "account_tax", "price_include_override", "varchar")
    cr.execute(
        """
            UPDATE account_tax t
               SET active = FALSE
              FROM ir_model_data md
             WHERE md.model = 'account.tax'
               AND md.res_id = t.id
               AND SUBSTRING(md.name, POSITION('_' in md.name) + 1) IN %s
        """,
        [DEACTIVATE_TAXES],
    )
    util.explode_execute(
        cr,
        """
            UPDATE account_tax t
               SET price_include_override = 'tax_included'
             WHERE price_include = TRUE
        """,
        table="account_tax",
        alias="t",
    )
    util.remove_column(cr, "account_tax", "price_include")
