[tool.black]
line-length = 120

[tool.isort]
profile = 'black'
line_length = 132
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'ODOOADDONS', 'LOCALFOLDER']
known_first_party = ['odoo', 'openerp']
known_odooaddons = ['odoo.addons', 'openerp.addons']
known_local_folder = ['odoo.upgrade', 'odoo.addons.base.maintenance.migrations', 'openerp.addons.base.maintenance.migrations']
