try:
    from odoo import Command
except ImportError:
    pass

from odoo.addons.base.maintenance.migrations import util
from odoo.addons.base.maintenance.migrations.testing import UpgradeCase, change_version


@change_version("saas~18.3")
class TestMigrateRunningTimers(UpgradeCase):
    def prepare(self):
        # Create user with an employee for that user.
        user_vals = {
            "name": "Timesheet Grid User",
            "login": "timesheet_grid_user",
            "email": "user@timesheet_grid.com",
        }
        if "group_ids" in self.env["res.users"]._fields:
            user_vals["group_ids"] = [Command.set([self.env.ref("hr_timesheet.group_hr_timesheet_user").id])]
        else:
            user_vals["groups_id"] = [Command.set([self.env.ref("hr_timesheet.group_hr_timesheet_user").id])]
        user = self.env["res.users"].create(user_vals)
        employee = self.env["hr.employee"].create(
            {
                "name": "User Employee Test",
                "user_id": user.id,
            }
        )

        # Create a project with `allow_timesheets=True`.
        project = self.env["project.project"].create(
            {
                "name": "Project 1",
                "allow_timesheets": True,
            }
        )
        # Create a task in that project.
        task = self.env["project.task"].create(
            {
                "name": "Task",
                "project_id": project.id,
            }
        )
        # Start a timer in that task with the user created.
        task.with_user(user).action_timer_start()

        # Create a timesheet without a task and another with the task created.
        timesheet_without_task = self.env["account.analytic.line"].create(
            {
                "name": "Timesheet 1",
                "employee_id": employee.id,
                "project_id": project.id,
            }
        )
        timesheet_without_task.with_user(user).action_timer_start()
        return user.id, employee.id, project.id, task.id, timesheet_without_task.id

    def check(self, init):
        if util.version_gte("saas~18.4"):
            # to re-introduce seems there is a timezone issue
            return
        user_id, employee_id, project_id, task_id, timesheet_without_task_id = init
        timers = self.env["timer.timer"].search(
            [
                ("user_id", "=", user_id),
                "|",
                ("res_id", "=", timesheet_without_task_id),
                ("parent_res_id", "=", task_id),
            ]
        )
        self.assertEqual(len(timers), 1, "Only one timer should be found.")
        self.assertEqual(timers.res_id, timesheet_without_task_id)
        self.assertEqual(timers.res_model, "account.analytic.line")
        self.assertFalse(
            timers.parent_res_id, "No parent res id should be set since the timesheet is not linked to a task."
        )
        self.assertFalse(
            timers.parent_res_model, "No parent res model should be set since the timesheet is not linked to a task."
        )
        timesheets = self.env["account.analytic.line"].search([("task_id", "=", task_id)])
        self.assertEqual(len(timesheets), 1, "A timesheet should be generated by the timer started in the task.")
        self.assertEqual(
            timesheets.employee_id.id,
            employee_id,
            "The employee set on the new timesheet should be the one of the user who started the timer.",
        )
        self.assertGreater(timesheets.unit_amount, 0, "The time elapsed should taken into account.")
        self.assertEqual(
            timesheets.project_id.id,
            project_id,
            "The project set on the newest timesheet should be the one of the task.",
        )
