from . import (
    test_add_dataset_to_odoo_charts,
    test_add_operator_to_gauge_chart,
    test_add_pivot,
    test_broken_revision_history,
    test_broken_revision_history_with_no_snapshot,
    test_chart_commands,
    test_create_table_command_change,
    test_image_attachment,
    test_insert_pivot,
    test_locale,
    test_missing_pivot_sorted_column,
    test_pivot_sorted_column,
    test_rename_pivot_functions,
    test_set_cumulated_start_odoo_chart,
    test_set_formatting_change,
    test_update_figure_commands,
)
