from odoo.upgrade import util


def migrate(cr, version):
    util.delete_unused(
        cr,
        "fleet.model_serie3",
        "fleet.model_astragtc",
        "fleet.model_insignia",
        "fleet.model_antara",
        "fleet.model_combotour",
        "fleet.model_a4",
        "fleet.model_classr",
        "fleet.model_q7",
        "fleet.model_mokka",
        "fleet.model_classs",
        "fleet.model_classcl",
        "fleet.model_classb",
        "fleet.model_serie5",
        "fleet.model_classa",
        "fleet.model_agila",
        "fleet.model_serie6",
        "fleet.model_seriex",
        "fleet.model_corsa",
        "fleet.model_a6",
        "fleet.model_a7",
        "fleet.model_classgl",
        "fleet.model_classe",
        "fleet.model_zafiratourer",
        "fleet.model_meriva",
        "fleet.model_serie7",
        "fleet.model_seriehybrid",
        "fleet.model_seriem",
        "fleet.model_ampera",
        "fleet.model_a5",
        "fleet.model_classsls",
        "fleet.model_classc",
        "fleet.model_classm",
        "fleet.model_seriez4",
        "fleet.model_a1",
        "fleet.model_a3",
        "fleet.model_tt",
        "fleet.model_serie1",
        "fleet.model_classglk",
        "fleet.model_q5",
        "fleet.model_q3",
        "fleet.model_astra",
        "fleet.model_zafira",
        "fleet.model_classcls",
        "fleet.model_classslk",
        "fleet.model_a8",
    )
    util.remove_record(cr, "fleet.model_category_4")
    util.remove_record(cr, "fleet.model_category_2")
