from . import (
    test_15_2_mega_menu,
    test_15_5_mobile,
    test_16_0_bs5,
    test_16_1_dynamic_snippets,
    test_16_2_move_popup,
    test_16_3_map_shapes,
    test_17_2_embed_code,
    test_17_2_mobile_order,
    test_17_3_remove_website_internal_user,
    test_17_5_unique_website_controller_page,
    test_17_5_website_controller_page_m2o_record,
    test_18_0_submenus,
    test_assets_management,
    test_cowed_layout,
    test_website_model,
)
