import logging

from odoo.tools import sql

from odoo.upgrade import util

_logger = logging.getLogger("odoo.upgrade.saas-16.1.1.3." + __name__)


def migrate(cr, version):
    # - Get all index generated by the ORM with the old naming convention
    # old naming convention : <table_name>_<field_name>_index.
    # - Rename them with the new naming convention: `sql.get_index_name`.
    # Note: the old index which doesn't follow the old convention or truncate because
    # it was too long are ignored.
    cr.execute(
        """
        SELECT col.table_name, col.column_name
          FROM information_schema.columns AS col
               JOIN pg_indexes AS pi ON col.table_name = pi.tablename
         WHERE col.table_schema = current_schema
               AND pi.indexname = col.table_name || '_' || col.column_name || '_index'
               -- skip known case of standard index that is not related to a field
               AND pi.indexname <> 'account_move_sequence_index'
        """
    )
    _logger.info("Rename %d indexes with the new naming convention.", cr.rowcount)
    queries = []
    for table_name, column_name in cr.fetchall():
        old_index_name = f"{table_name}_{column_name}_index"
        new_index_name = sql.make_index_name(table_name, column_name)
        queries.append(f'ALTER INDEX "{old_index_name}" RENAME TO "{new_index_name}"')

    util.parallel_execute(cr, queries)

    util.remove_menus(
        cr,
        [
            util.ref(cr, "base.menu_board_root"),
            util.ref(cr, "base.menu_reporting_dashboard"),
            util.ref(cr, "base.menu_reporting_config"),
        ],
    )

    util.remove_view(cr, "base.view_module_category_tree")

    util.remove_field(cr, "ir.ui.view", "field_parent")
    util.remove_field(cr, "ir.module.category", "module_nr")

    # The `Warning` exception is no more available in server actions
    cr.execute(
        r"""
            UPDATE ir_act_server
               SET code = regexp_replace(code, '\yWarning *\(', 'UserError(', 'g')
             WHERE code ~ '\yWarning *\('
        """
    )
