from odoo.upgrade import util


def migrate(cr, version):
    # Remove UBL 2.0 and 2.1 templates
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_DebitNote")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_CreditNote")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_Invoice")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_DebitNoteType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_CreditNoteType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_InvoiceType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_CommonType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_DebitNoteLineType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_CreditNoteLineType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_InvoiceLineType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_CommonLineType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_ExchangeRateType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_MonetaryTotalType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_InvoicePeriodType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_DeliveryType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_ResponseType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_SignatureType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_AllowanceChargeType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_TaxTotalType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_TaxCategoryType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_PaymentTermsType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_PaymentMeansType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_PartyType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_20_AddressType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_DebitNoteType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_CreditNoteType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_InvoiceLineType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_InvoiceType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_DebitNoteLineType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_CreditNoteLineType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_PartyType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_PaymentTermsType")
    util.remove_view(cr, "account_edi_ubl_cii.ubl_21_AddressType")
