import logging

from odoo.addons.base.maintenance.migrations import util

_logger = logging.getLogger(__name__)


def migrate(cr, version):
    if util.version_gte("saas~18.1"):
        _check_indexes(cr)


def _check_indexes(cr):
    """Warn about using an index with a WHERE on boolean values."""
    cr.execute(r"""
      SELECT i.indexname, i.tablename, i.indexdef
        FROM pg_indexes i
       WHERE i.indexdef ~* '\yWHERE\y.+?\y(?:TRUE|FALSE|active)\y'
         AND NOT (i.indexdef ~* 'IS (NOT )?TRUE')
         AND i.schemaname = 'public'
             -- remove ORM-managed indexes
         AND i.indexname NOT IN
             (SELECT c.name
                FROM ir_model_constraint c
               WHERE c.definition IS NOT NULL)
    ORDER BY i.indexname
    """)
    warn_indexes = []
    for index_name, table_name, index_def in cr.fetchall():
        condition = index_def.split("WHERE", maxsplit=1)[1]
        warn_indexes.append("{!r} on {!r} with condition `{}`".format(index_name, table_name, condition))
    if warn_indexes:
        _logger.warning(
            "Where clauses generated by the ORM for boolean fields are now always IS TRUE or IS NOT TRUE. "
            "The following indexes need to be reviewed:\n%s",
            "\n".join(warn_indexes),
        )
